CREATE TABLE IF NOT EXISTS routines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    cover_image_url TEXT NOT NULL DEFAULT '',
    emoji TEXT NOT NULL DEFAULT '🏋️',
    color TEXT NOT NULL DEFAULT 'bg-blue-600',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);